stages:
  - deploy
deploy_application_to_the_server:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache docker-compose openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    
  script:
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$SERVER_IP "cd $FILE_PATH && git pull origin main && docker compose up -d --build --remove-orphans"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  tags:
    - "ai-chatbot-runner"
    - "react-runner"
